# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.logspout.description="Logspout"
LABEL io.bluebeluga.logspout.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.logspout.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.logspout.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

ENTRYPOINT ["/bin/logspout"]
VOLUME /mnt/routes
EXPOSE 8000

COPY files/. /src
RUN cd /src && ./build.sh "$(cat VERSION)"

ONBUILD COPY ./modules.go /src/modules.go
ONBUILD RUN cd /src && ./build.sh "$(cat VERSION)-custom"
